In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('healthcare-dataset-stroke-data.csv')
data

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64  
 4   heart_disease      5110 non-null   int64  
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB


In [4]:
data.isna().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [5]:

data.columns=data.columns.str.strip()
data.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [6]:
data.drop(['id'],axis=1,inplace=True)
data

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1     Female  61.0             0              0          Yes  Self-employed   
2       Male  80.0             0              1          Yes        Private   
3     Female  49.0             0              0          Yes        Private   
4     Female  79.0             1              0          Yes  Self-employed   
...      ...   ...           ...            ...          ...            ...   
5105  Female  80.0             1              0          Yes        Private   
5106  Female  81.0             0              0          Yes  Self-employed   
5107  Female  35.0             0              0          Yes  Self-employed   
5108    Male  51.0             0              0          Yes        Private   
5109  Female  44.0             0              0          Yes       Govt_job   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             202.21   NaN     never smoked       1  
2             Rural             105.92  32.5     never smoked       1  
3             Urban             171.23  34.4           smokes       1  
4             Rural             174.12  24.0     never smoked       1  
...             ...                ...   ...              ...     ...  
5105          Urban              83.75   NaN     never smoked       0  
5106          Urban             125.20  40.0     never smoked       0  
5107          Rural              82.99  30.6     never smoked       0  
5108          Rural             166.29  25.6  formerly smoked       0  
5109          Urban              85.28  26.2          Unknown       0  

[5110 rows x 11 columns]

In [7]:
data['ever_married'].unique()

array(['Yes', 'No'], dtype=object)

In [8]:
data['ever_married']=data['ever_married'].map({'No':0,'Yes':1})
data['ever_married'].unique()

array([1, 0], dtype=int64)

In [9]:
data['Residence_type'].unique()

array(['Urban', 'Rural'], dtype=object)

In [10]:
data['Residence_type']=data['Residence_type'].map({'Urban':1,'Rural':0})
data['Residence_type'].unique()

array([1, 0], dtype=int64)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             5110 non-null   object 
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64  
 3   heart_disease      5110 non-null   int64  
 4   ever_married       5110 non-null   int64  
 5   work_type          5110 non-null   object 
 6   Residence_type     5110 non-null   int64  
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                4909 non-null   float64
 9   smoking_status     5110 non-null   object 
 10  stroke             5110 non-null   int64  
dtypes: float64(3), int64(5), object(3)
memory usage: 439.3+ KB


In [12]:
mean=data['bmi'].mean()
data['bmi']=data['bmi'].fillna(mean)
data['bmi']
#filling the nana values with mean of bmi 

0       36.600000
1       28.893237
2       32.500000
3       34.400000
4       24.000000
          ...    
5105    28.893237
5106    40.000000
5107    30.600000
5108    25.600000
5109    26.200000
Name: bmi, Length: 5110, dtype: float64

In [13]:
for column in data.columns:
    if(column!='age' and column!='bmi' and len(data[column].unique())>2):
        print(data[column].unique(),column)
#These columns have more than 2 categorical data which we need to convert to numerical data before fitting the dataset into a model

['Male' 'Female' 'Other'] gender
['Private' 'Self-employed' 'Govt_job' 'children' 'Never_worked'] work_type
[228.69 202.21 105.92 ...  82.99 166.29  85.28] avg_glucose_level
['formerly smoked' 'never smoked' 'smokes' 'Unknown'] smoking_status


### One Hot Encoding

In [14]:
one_hot_encoded_df=pd.get_dummies(data,columns=['gender','work_type','smoking_status'],drop_first=True)
one_hot_encoded_df=one_hot_encoded_df.astype(int)
data=one_hot_encoded_df
data
#Drop first =True is for removing one feature from multiple unique features in a column means all rest features are 0 this feature is 1 its automatically understood

age  hypertension  heart_disease  ever_married  Residence_type  \
0      67             0              1             1               1   
1      61             0              0             1               0   
2      80             0              1             1               0   
3      49             0              0             1               1   
4      79             1              0             1               0   
...   ...           ...            ...           ...             ...   
5105   80             1              0             1               1   
5106   81             0              0             1               1   
5107   35             0              0             1               0   
5108   51             0              0             1               0   
5109   44             0              0             1               1   

      avg_glucose_level  bmi  stroke  gender_Male  gender_Other  \
0                   228   36       1            1             0   
1                   202   28       1            0             0   
2                   105   32       1            1             0   
3                   171   34       1            0             0   
4                   174   24       1            0             0   
...                 ...  ...     ...          ...           ...   
5105                 83   28       0            0             0   
5106                125   40       0            0             0   
5107                 82   30       0            0             0   
5108                166   25       0            1             0   
5109                 85   26       0            0             0   

      work_type_Never_worked  work_type_Private  work_type_Self-employed  \
0                          0                  1                        0   
1                          0                  0                        1   
2                          0                  1                        0   
3                          0                  1                        0   
4                          0                  0                        1   
...                      ...                ...                      ...   
5105                       0                  1                        0   
5106                       0                  0                        1   
5107                       0                  0                        1   
5108                       0                  1                        0   
5109                       0                  0                        0   

      work_type_children  smoking_status_formerly smoked  \
0                      0                               1   
1                      0                               0   
2                      0                               0   
3                      0                               0   
4                      0                               0   
...                  ...                             ...   
5105                   0                               0   
5106                   0                               0   
5107                   0                               0   
5108                   0                               1   
5109                   0                               0   

      smoking_status_never smoked  smoking_status_smokes  
0                               0                      0  
1                               1                      0  
2                               1                      0  
3                               0                      1  
4                               1                      0  
...                           ...                    ...  
5105                            1                      0  
5106                            1                      0  
5107                            1                      0  
5108                            0                      0  
5109                            0                    

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   age                             5110 non-null   int32
 1   hypertension                    5110 non-null   int32
 2   heart_disease                   5110 non-null   int32
 3   ever_married                    5110 non-null   int32
 4   Residence_type                  5110 non-null   int32
 5   avg_glucose_level               5110 non-null   int32
 6   bmi                             5110 non-null   int32
 7   stroke                          5110 non-null   int32
 8   gender_Male                     5110 non-null   int32
 9   gender_Other                    5110 non-null   int32
 10  work_type_Never_worked          5110 non-null   int32
 11  work_type_Private               5110 non-null   int32
 12  work_type_Self-employed         5110 non-null   int32
 13  wor

In [16]:
X=data.drop(['stroke'],axis=1)
y=data[['stroke']]

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train

age  hypertension  heart_disease  ever_married  Residence_type  \
802    79             0              0             1               0   
3927   62             0              0             1               1   
2337   21             0              0             0               0   
3910   31             0              0             1               1   
1886   31             0              0             0               0   
...   ...           ...            ...           ...             ...   
4426   43             0              0             1               0   
466    61             1              0             1               0   
3092    1             0              0             0               1   
3772   80             0              0             1               0   
860    46             0              0             1               0   

      avg_glucose_level  bmi  gender_Male  gender_Other  \
802                 112   28            1             0   
3927                 88   36            0             0   
2337                 59   33            0             0   
3910                 65   30            1             0   
1886                 59   19            0             0   
...                 ...  ...          ...           ...   
4426                 88   30            1             0   
466                 170   60            0             0   
3092                 97   17            0             0   
3772                196   31            1             0   
860                 100   50            0             0   

      work_type_Never_worked  work_type_Private  work_type_Self-employed  \
802                        0                  0                        1   
3927                       0                  1                        0   
2337                       0                  1                        0   
3910                       0                  0                        0   
1886                       0                  1                        0   
...                      ...                ...                      ...   
4426                       0                  0                        0   
466                        0                  1                        0   
3092                       0                  0                        0   
3772                       0                  0                        1   
860                        0                  1                        0   

      work_type_children  smoking_status_formerly smoked  \
802                    0                               1   
3927                   0                               0   
2337                   0                               0   
3910                   0                               1   
1886                   0                               0   
...                  ...                             ...   
4426                   0                               0   
466                    0                               0   
3092                   1                               0   
3772                   0                               1   
860                    0                               0   

      smoking_status_never smoked  smoking_status_smokes  
802                             0                      0  
3927                            0                      0  
2337                            1                      0  
3910                            0                      0  
1886                            1                      0  
...                           ...                    ...  
4426                            1                      0  
466                             0                      1  
3092                            0                      0  
3772                            0                      0  
860                             0                      1  

[4088 rows x 16 columns]

In [18]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)


In [19]:
model=LogisticRegression()
penalty = ['l1', 'l2', 'elasticnet']  # Regularization methods
C_values = [100, 10, 1.0, 0.1, 0.01]  # Regularization strength
solver = ['liblinear', 'saga']  # Only solvers compatible with l1 and elasticnet
param_grid = {
    'penalty': penalty,
    'C': C_values,
    'solver': solver
}
param_grid

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['liblinear', 'saga']}

In [20]:
cv=StratifiedKFold()
gridcv=GridSearchCV(estimator=model,param_grid=param_grid,scoring='accuracy',cv=cv)
randomcv=RandomizedSearchCV(estimator=model,param_distributions=param_grid,scoring='accuracy',cv=cv)
gridcv.fit(X_train,y_train)
randomcv.fit(X_train,y_train)

c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\mahap\OneDrive\Desktop\C++,JS python cod

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['liblinear', 'saga']},
                   scoring='accuracy')

In [21]:
gridcv

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['liblinear', 'saga']},
             scoring='accuracy')

In [22]:
gridcv.best_params_

{'C': 0.1, 'penalty': 'l2', 'solver': 'saga'}

In [23]:
randomcv.best_params_

{'solver': 'liblinear', 'penalty': 'l2', 'C': 0.01}

In [24]:
pred1=gridcv.predict(X_test)
pred2=randomcv.predict(X_test)

In [25]:
accuracy1=accuracy_score(y_test,pred1)
print("The accuracy score for model with grid search cv is",accuracy1)

The accuracy score for model with grid search cv is 0.9393346379647749


In [26]:
accuracy2=accuracy_score(y_test,pred2)
print("The accuracy score for model with random search cv is",accuracy2)

The accuracy score for model with random search cv is 0.9393346379647749


In [27]:
#Both the search cv gives same accuracy
import pickle
with open('stroke-prediction-model.pkl','wb') as file:
    pickle.dump(gridcv,file)
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)
#Pickling is for storing the essential objects in hard disk so that they can be loaded in flask app,scaler to just transform the new data and stroke prediction model to predict from them 

In [28]:
pred1

array([0, 0, 0, ..., 0, 0, 0])

In [29]:
pred2

array([0, 0, 0, ..., 0, 0, 0])

In [30]:
print(confusion_matrix(y_test,pred1))
print(confusion_matrix(y_test,pred2))
#The total false negatives is also 0 which would have been very big blunder


[[960   0]
 [ 62   0]]
[[960   0]
 [ 62   0]]


In [31]:
data.columns

Index(['age', 'hypertension', 'heart_disease', 'ever_married',
       'Residence_type', 'avg_glucose_level', 'bmi', 'stroke', 'gender_Male',
       'gender_Other', 'work_type_Never_worked', 'work_type_Private',
       'work_type_Self-employed', 'work_type_children',
       'smoking_status_formerly smoked', 'smoking_status_never smoked',
       'smoking_status_smokes'],
      dtype='object')